#routes that render pages
filmIndexPage:
  path: /
  controller: App\Controller\FilmsController::filmIndexPage

filmDetailsPage:
  path: /films/details/{id}
  controller: App\Controller\FilmsController::filmDetailsPage
  methods: GET

updateFilmPage:
  path: /films/update/{id}
  controller: App\Controller\FilmsController::updateFilmPage
  methods: GET|POST

addFilmPage:
  path: /films/add
  controller: App\Controller\FilmsController::addFilmPage
  methods: GET|POST

manageGenresPage:
  path: /genres
  controller: App\Controller\GenresController::manageGenresPage

manageDirectorsPage:
  path: /directors
  controller: App\Controller\DirectorsController::manageDirectorsPage

#routes that modify the database
deleteFilm:
  path: /films/delete/{id}
  controller: App\Controller\FilmsController::deleteFilm
  methods: DELETE

deleteAllFilms:
  path: /films/clear
  controller: App\Controller\FilmsController::deleteAllFilms
  methods: DELETE

deleteAllGenres:
  path: /genres/clear
  controller: App\Controller\GenresController::deleteAllGenres
  methods: DELETE

deleteGenre:
  path: /genres/delete/{id}
  controller: App\Controller\GenresController::deleteGenre
  methods: DELETE

deleteAllDirectors:
  path: /directors/clear
  controller: App\Controller\DirectorsController::deleteAllDirectors
  methods: DELETE

deleteDirector:
  path: /directors/delete/{id}
  controller: App\Controller\DirectorsController::deleteDirector
  methods: DELETE




