
#actions that render pages

indexFilm:
   path: /
   controller: App\Controller\FilmsController::index

updateFilmPage:
  path: /films/update/{id}
  controller: App\Controller\FilmsController::updateFilmPage

#actions that modify the database

deleteFilm:
  path: /films/delete/{id}
  controller: App\Controller\FilmsController::deleteFilm
  methods: GET

addFilm:
   path: /films/add
   controller: App\Controller\FilmsController::addFilm
   methods: POST

findMatchingFilm:
   path: /films/{searchBy}/{input}
   controller: App\Controller\FilmsController::findMatching
   methods: GET


showAllFilms:
   path: /films/all
   controller: App\Controller\FilmsController::showAll
   methods: GET
