#routes that render pages
filmIndexPage:
  path: /
  controller: App\Controller\FilmsController::filmIndexPage

filmDetailsPage:
  path: /films/details/{id}
  controller: App\Controller\FilmsController::filmDetailsPage

updateFilmPage:
  path: /films/update/{id}
  controller: App\Controller\FilmsController::updateFilmPage

addFilmPage:
  path: /films/add
  controller: App\Controller\FilmsController::addFilmPage

manageGenresPage:
  path: /genres
  controller: App\Controller\GenresController::manageGenresPage

manageDirectorsPage:
  path: /directors
  controller: App\Controller\DirectorsController::manageDirectorsPage

#routes that modify the database
deleteFilm:
  path: /films/delete/{id}
  controller: App\Controller\FilmsController::deleteFilm
  methods: GET

deleteGenre:
  path: /genres/delete/{id}
  controller: App\Controller\GenresController::deleteGenre
  methods: GET

deleteDirector:
  path: /directors/delete/{id}
  controller: App\Controller\DirectorsController::deleteDirector
  methods: GET



